### ISSUE TITLE
Why is admin > 6.6 needed?

### ISSUE THREAD

**Issue by SKB-CGN** [klein0r/ioBroker.awtrix-light#51]
### The problem

Hi,
Why is admin version 6.6 needed, while 6.3 is official?

### Version of nodejs

20

### Version of ioBroker js-controller

N/a

### Version of Adapter

0.5.1

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by mtoensing** [comment]
Same here. I am unable to use this adapter on a Pi4 with ioBroker image because admin is on 6.3.5

**Comment by SKB-CGN** [comment]
I suppose, it has something to do with the admin itself - it changed the depency to admin 6.3, but I am not able to create any custom app. Notification can be sent to the clock.

**Comment by mtoensing** [comment]
But how can I update to admin 6.6 with the official pi 4 image?

**Comment by SKB-CGN** [comment]
Then, beta repository

**Comment by klein0r** [comment]
Developing adapters is so much fun.... people add feature requests over feature requests and want more and more features... so the configuration in a table component wasn't possible anymore

So I've invested some days (!!!) to create a new jsonConfig Component for the admin (= accordion). And this component is devlivered with admin >= 6.6.0. *And after all, I have to explain why I did that...* 😞

You can use an older version of the admin adapter, but you won't be able to create any app (since the component is missing).

**Comment by klein0r** [comment]
**You have to install the adapter via beta repository. Just don't use GitHub installs and you don't have problems (since you also get the newest admin beta in that case)**

**Comment by klein0r** [comment]
> i changed the depency to admin 6.3

Hint: The dependency wasn't set to >= 6.6.0 to annoy you. That's not very smart

**Comment by mtoensing** [comment]
Thanks. The hint to the beta repo helped. And regarding this: 

_Developing adapters is so much fun.... people add feature requests over feature requests and want more and more features..._ 

When you start a open-source project, and it becomes successful, you start as the entrepreneur and end up as the janitor.  Made the same experience with some of my projects (mtoensing/Docker-Minecraft-PaperMC-Server and mtoensing/simpletoc) So my decision was: keep it simple. Don't add everything just because you can. And don't merge every PR. Or the codebase will get so big that nobody, including you, can handle it. It is better to have something small that is maintainable rather then to sit on a pile of s... that no one can update. =) But this is just my opinion.

**Comment by klein0r** [comment]
> So my decision was: keep it simple.

Indeed. But: It is simple. Just use the beta repository and fulfil the dependencies 😄 
No fancy GitHub installations, just 2 clicks.

**Comment by mtoensing** [comment]
I did want to offend you. You did everything right. As i said: After you told me about the beta repo everything is fine. 

I commented on your sentence about feature requests from the community and so on. I related to that. =)
